# Generated by Django 3.2.12 on 2024-11-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazwaAplikacji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
